#!/bin/sh

# restore the workspace
i3-msg 'workspace hdmi; append_layout ~/.config/i3/workspace-hdmi.json'
i3-msg 'workspace 1; append_layout ~/.config/i3/workspace.json'

# notification events
dunst &

# start some shells
for i in $(seq 4); do urxvt & done

# email
urxvt -name email -e mutt -e 'set quit=ask-no' &

emacs &

# work profile
chromium  --profile-directory='Profile 1' &

# GUI tools
slack &
signal &
gpmdp &
# "Trello External Window"
gtk-launch chrome-gkcknpgdmiigoagkcoglklgaagnpojed-Profile_1.desktop &
