#!/bin/sh

# restore the workspace
i3-msg 'workspace 1; append_layout ~/.config/i3/workspace-1.json'

# notification events
dunst &

# start some shells
for i in $(seq 3); do urxvt & done

emacs &

# work profile
chromium  --profile-directory='Profile 1' &

# GUI tools
slack &
signal &
