#!/bin/sh

# restore the
i3-msg 'workspace 1; append_layout ~/.config/i3/workspace-1.json'

# some shells
urxvt &
urxvt &

emacs &

# work profile
chromium  --profile-directory='Profile 1' &

# GUI tools
slack &
# Signal
gtk-launch chrome-bikioccmkafdpakkkcpdbppfkghcmihk-Default.desktop &

# just run these as needed now
# 1password
# pwsafe
