screenshot-format=png

vo=gpu-next
hwdec=auto

#gpu-context=waylandvk
#gpu-api=vulkan

# force-window=immediate

ytdl-format='bestvideo[width<=?1920][height<=?1080]+bestaudio'

# blend-subtitles=yes

[hdr]
profile-desc=config HDR ICC
icc-profile-auto=yes
target-prim=bt.2020
target-peak=400

[reduce-judder]
profile-desc=enable temporal interpolation
interpolation=yes
video-sync=display-resample
tscale=sphinx
tscale-window=quadric
tscale-radius=1.025
tscale-blur=0.69
tscale-clamp=0.0
