general {
    lock_cmd = pidof swaylock || swaylock -f -F -c 000000
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = niri msg action power-on-monitors
}
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}
listener {
    timeout = 330
    on-timeout = niri msg action power-on-monitors
    on-resume = niri msg action power-off-monitors
}
