# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.squidowl.org/configuration/index.html

[servers.liberachat]
server = "irc.libera.chat"
nickname = "smason"
nick_password_file = "/home/smason/.config/halloy/auth/liberachat"
channels = ["#archlinux"] #, "#emersion"]

[servers.oftc]
server = "irc.oftc.net"
nickname = "smason"
nick_password_file = "/home/smason/.config/halloy/auth/oftc"
channels = ["#pwmt"]
