[[language]]
name = "python"
file-types = ["py", "pyx"]

[[language]]
name = "rust"
auto-format = false

[[language]]
name = "markdown"
language-server = { command = "ltex-ls", args=["--log-file=/tmp"] }

[language.config.ltex]
language = "en-GB"
