[[language]]
name = "python"
file-types = ["py", "pyx"]

[[language]]
name = "rust"
auto-format = false

[[language]]
name = "markdown"
text-width = 72
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
