[language-server.ty]
command = "ty"
args = ["server"]

[language-server.qmlls]
command = "qmlls6"
args = ["-E"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls]
dialect = "British"
linters = { UseTitleCase = false, SentenceCapitalization = false }

[language-server.tinymist.config.preview.background]
enabled = true
args = ["--data-plane-host=127.0.0.1:0", "--invert-colors=never", "--open"]

[[language]]
name = "python"
language-id = "python"
auto-format = true
language-servers = ["ty", "ruff"]
file-types = ["py", "pyx", "ipynb"]
comment-token = "#"
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", ".venv", ".git", ".jj"]

[[language]]
name = "rust"
auto-format = false

[[language]]
name = "markdown"
rulers = [72]
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
language-servers = ["marksman", "markdown-oxide", "harper-ls"]

[[language]]
name = "plaintext"
scope = "text.txt"
rulers = [72, 80]
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
language-servers = ["default-servers", "harper-ls"]
# enable for *.txt, if you don't want this run ":lang text"
file-types = ["txt"]

[[language]]
name = "git-commit"
language-servers = ["harper-ls"]
